### ISSUE TITLE
Help with image ratios

### ISSUE THREAD

**Issue by tiearcher** [tiearcher/profile-page#1]
@Wendywarren @KarenMendozaGarza
How would I go about keeping the images in the portfolio section at their original aspect ratio? They're a mix of landscape and portrait and I'd like them to stay the way the file is built instead of all being converted to portrait. Ideally they'd all be the correct width to keep the grid intact, just with varying heights to preserve the ratio.

**Comment by wendywarren** [comment]
Great work so far @tiearcher!

What I would do is remove the width, height and object-fit properties for images within your grid.

<img width="1326" alt="Screen Shot 2022-09-23 at 1 10 08 PM" src="https://user-images.githubusercontent.com/12865609/192016035-329db97f-0b7a-4e9d-a6c5-e105970f26da.png">

This will allow you to display the full piece as intended. The images are set to take 100% of the available space within the column.

Let me know if you have any other questions. :)

Thanks,
Wendy
